import {L_SYSTEM_PRESETS_NAMES} from "./LSystemOptionSelect.types.ts";
import {LSystemInitOptions} from "../../utils/L-system.ts";

export const lSystemOptionsPresets: Record<`${L_SYSTEM_PRESETS_NAMES}`, LSystemInitOptions> = {
    kochSnowflake: {
        S: ['F', '+', '+', 'F', '+', '+', 'F'],
        F: ['F', '-', 'F', '+', '+', 'F', '-', 'F'],
        X: [],
        Y: [],
        alpha: 60,
        stepLength: 5,
        initX: 0,
        initY: 200,
    },
    dragonCurve: {
        S: ['F', 'X'],
        F: ['F'],
        X: ['X', '+', 'Y', 'F', '+'],
        Y: ['-', 'F', 'X', '-', 'Y'],
        alpha: 90,
        stepLength: 3,
        initX: 500,
        initY: 350,
    },
    sierpinskiTriangle: {
        S: ['F', 'X', 'F', '-', '-', 'F', 'F', '-', '-', 'F', 'F'],
        F: ['F', 'F'],
        X: ['-', '-', 'F', 'X', 'F', '+', '+', 'F', 'X', 'F', '+', '+', 'F', 'X', 'F', '-', '-'],
        Y: [],
        alpha: 60,
        stepLength: 4,
        initX: 0,
        initY: 700,
    },
    hilbertCurve: {
        S: ['X'],
        F: ['F'],
        X: ['-', 'Y', 'F', '+', 'X', 'F', 'X', '+', 'F', 'Y', '-'],
        Y: ['+', 'X', 'F', '-', 'Y', 'F', 'Y', '-', 'F', 'X', '+'],
        alpha: 90,
        stepLength: 3,
        initX: 0,
        initY: 700,
    },
    tree1: {
        S: ['F'],
        F: ['F', '[', '+', 'F', ']', 'F', '[', '-', 'F', ']', 'F'],
        X: [],
        Y: [],
        alpha: 25.7,
        stepLength: 3,
        initX: 0,
        initY: 350,
    },
    tree2: {
        S: ['F'],
        F: ['F', '[', '+', 'F', ']', 'F', '[', '-', 'F', ']', '[', 'F', ']'],
        X: [],
        Y: [],
        alpha: 20,
        stepLength: 3,
        initX: 0,
        initY: 350,
    },
    tree3: {
        S: ['X'],
        F: ['F', 'F'],
        X: ['F', '[', '+', 'X', ']', '[', '-', 'X', ']', 'F', 'X'],
        Y: [],
        alpha: 25.7,
        stepLength: 3,
        initX: 0,
        initY: 350,
    },
    tree4: {
        S: ['F'],
        F: ['-', 'F', '[', '-', 'F', '+', 'F', '-', 'F', ']', '+', '[', '+', 'F', '-', 'F', '-', 'F', ']'],
        X: [],
        Y: [],
        alpha: 20,
        stepLength: 30,
        initX: 500,
        initY: 350,
    },
}
